version: 2

sources:
  - name: northwind          #Escolhido por mim e usardo dentro do DBT.
    description: "Dados brutos do sistema financeiro da empresa"
    schema: project_one_dw_seeds
    loader: bigquery
    loaded_at_field: data_carga    #Coluna que será gravada junto a tabela e dirá a data da carga ; A coluna tem que estar criada na tabela fonte
#    meta:                         #Metadados da Source. Dados de sensibilidade.
#      owner: "Empresa byty"
    tags: [finance, staging]
#     freshness:
# 		  warn_after: {count: 1, period: day}     #Alerta: Não para, só avisa.  #Nesse caso, alertará se ficar um dia sem atualizar.
#       error_after: {count: 2, period: day}    #Alerta: Para e avisa.        #Nesse caso, irá parar e alertar se ficar pelo menos dois dias sem atualizar.
    tables:
      - name: categories
        description: "Tabela com as categorias de produtos"
        columns:
          - name: category_id
            description: "ID da categoria"
          - name: category_name
            description: "Nome da categoria"
          - name: description
            description: "Descrição da categoria"
          - name: picture
            description: "Imagem da categoria"
      - name: orders
        description: "Tabela com os pedidos de clientes"
        columns:
          - name: order_id
            description: "ID do pedido"
          - name: customer_id
            description: "ID do cliente"
          - name: employee_id
            description: "ID do funcionário"
          - name: order_date
            description: "Data do pedido"