
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'project_one'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'project_one'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  project_one:
    staging:                  #pasta staging dentro da pasta models
      materialized: table
      tags: ['staging']
      staging_sap:
        materialized: table
        schema: staging_sap #custom_schema
        tags: ['staging_sap']
      staging_northwind:
        materialized: table
        schema: staging_northwind #custom_schema
        tags: ['staging_northwind']
    intermediate:             #pasta intermediate dentro da pasta models
      materialized: table
      tags: ['intermediate']
    marts:                     #pasta marts dentro da pasta models
      schema: marts
      materialized: table
      tags: ['marts']
seeds:
  project_one:
    schema: seeds   #Nome do schema criado vai concatenar com nome schema padrão. Ex: dbt_seeds
    tags: ['seeds']
